<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.applitools</groupId>
  <artifactId>testng-selenium-pom</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <selenium.version>4.27.0</selenium.version>
    <testng.version>7.10.2</testng.version>
    <surefire.version>3.5.2</surefire.version>
    <applitools.version>5.83.19 </applitools.version>
    <applitools.images.version>5.81.3</applitools.images.version>
    <extentreports.version>5.1.1</extentreports.version>
  </properties>

  <dependencies>
    <!-- Selenium WebDriver (includes Selenium Manager for auto driver setup) -->
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>${selenium.version}</version>
    </dependency>

    <!-- TestNG -->
    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>${testng.version}</version>
    </dependency>

    <!-- Applitools Eyes SDK (Ultrafast Grid) -->
    <dependency>
      <groupId>com.applitools</groupId>
      <artifactId>eyes-selenium-java5</artifactId>
      <version>${applitools.version}</version>
    </dependency>
    <!-- This is the Applitools Images Java SDK -->
    <dependency>
     <groupId>com.applitools</groupId>
     <artifactId>eyes-images-java5</artifactId>
     <version>${applitools.images.version}</version>
    </dependency>

    <!-- Extent Reports -->
    <dependency>
      <groupId>com.aventstack</groupId>
      <artifactId>extentreports</artifactId>
      <version>${extentreports.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire.version}</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>src/test/resources/testng.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
